// lib/compensation/claimLetter.ts
//
// Plain-text claim letter the passenger sends themselves. Wording is
// deliberately non-definitive ("may be entitled"): eligibility can't be
// established from flight data alone (extraordinary circumstances, notice
// dates), and FlightAgent does not represent the passenger.
//
// The amount always comes from the compensation engine result, never from
// client input or the delay length.

import type { CompensationInput, CompensationResult } from './engine';

export const NOT_LEGAL_ADVICE =
    'This document was generated by FlightAgent from publicly reported flight data. It is not legal advice.';

export interface ClaimLetterInput {
    passengerName: string;
    flightNumber: string;
    origin: string;
    destination: string;
    scheduledDate: string;
    disruption: 'DELAY' | 'CANCELLATION';
    arrivalDelayMinutes: number | null;
    compensation: CompensationResult;
    today: Date;
}

/** Placeholder names the UI used to send; never put them on a letter. */
export function isRealPassengerName(name: string | null | undefined): name is string {
    const trimmed = name?.trim() ?? '';
    return trimmed.length >= 2 && trimmed.toLowerCase() !== 'passenger';
}

export function regulationReference(regime: CompensationResult['regime']): string {
    return regime === 'UK261'
        ? 'Regulation (EC) No 261/2004 as retained in UK law (UK261), Article 7'
        : 'Regulation (EC) No 261/2004, Article 7';
}

export function formatCompensationAmount(result: CompensationResult): string | null {
    if (result.status !== 'LIKELY_ELIGIBLE' || result.amount === null || !result.currency) return null;
    return `${result.currency} ${result.amount}`;
}

/** Engine input for a flight given as number + endpoints (no trip record). */
export function compensationInputFromFlight(details: {
    flightNumber: string;
    origin: string;
    destination: string;
    disruption: 'DELAY' | 'CANCELLATION';
    arrivalDelayMinutes: number | null;
}): CompensationInput {
    const carrier = details.flightNumber.trim().toUpperCase().match(/^([A-Z0-9]{2})\d/)?.[1] ?? null;
    return {
        disruption: details.disruption,
        carrierIata: carrier,
        originIata: details.origin.toUpperCase(),
        finalDestinationIata: details.destination.toUpperCase(),
        arrivalDelayMinutes: details.arrivalDelayMinutes,
    };
}

const formatDate = (date: Date) => new Intl.DateTimeFormat('en-GB', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
}).format(date);

/**
 * Returns null unless the engine says LIKELY_ELIGIBLE — a letter must not be
 * produced for a flight the engine rejected or could not assess.
 */
export function buildClaimLetter(input: ClaimLetterInput): string | null {
    const amount = formatCompensationAmount(input.compensation);
    if (!amount) return null;

    const incident = input.disruption === 'CANCELLATION'
        ? 'According to the information currently available, this flight was cancelled.'
        : `According to the information currently available, the flight reached its final destination about ${
            input.arrivalDelayMinutes !== null ? `${Math.round((input.arrivalDelayMinutes / 60) * 10) / 10} hours` : 'three or more hours'
        } late.`;

    return [
        formatDate(input.today),
        '',
        `Passenger: ${input.passengerName.trim()}`,
        '',
        'Dear Customer Relations Team,',
        '',
        `I am writing regarding flight ${input.flightNumber} from ${input.origin} to ${input.destination}, scheduled for ${input.scheduledDate}.`,
        '',
        incident,
        `I believe I may be entitled to compensation of ${amount} under ${regulationReference(input.compensation.regime)}, and I ask you to review this request.`,
        '',
        'If you consider that extraordinary circumstances apply, please tell me which circumstances you rely on and provide the supporting evidence.',
        '',
        'I would be grateful for a written response within 14 days.',
        '',
        'Yours faithfully,',
        input.passengerName.trim(),
        '',
        '--',
        NOT_LEGAL_ADVICE,
    ].join('\n');
}
