/**
 * MONITORING TRANSPARENCY MODEL
 *
 * Defines explicit monitoring states and data source types for user-facing transparency.
 * Governs what is shown as "actively monitored" vs "estimated".
 * Used in tracked itinerary pages, Guardian pages, and route tracking displays.
 *
 * Rules:
 * - NEVER imply real-time airline-grade monitoring
 * - ALWAYS show snapshot age and last-check time to the user
 * - STALE / ESTIMATED_ONLY states must suppress strong reassurance wording
 * - Data source must be disclosed in any monitoring summary
 */

// ---------------------------------------------------------------------------
// Core enums
// ---------------------------------------------------------------------------

export type MonitoringState =
    | 'ACTIVE'          // Periodic checks running normally; snapshot is recent
    | 'CHECKING'        // A snapshot fetch is currently in progress
    | 'DELAYED'         // Expected check window has passed; check has not arrived yet
    | 'STALE'           // Snapshot age exceeds freshness threshold
    | 'LIMITED_DATA'    // Monitoring active but data coverage is incomplete
    | 'ESTIMATED_ONLY'  // No provider check performed; all data is estimated
    | 'ERROR';          // Monitoring encountered a failure

export type MonitoringDataSource =
    | 'LIVE_PROVIDER_DATA'        // Near-real-time airline / GDS feed
    | 'PERIODIC_PROVIDER_CHECK'   // Scheduled provider check (not streaming)
    | 'HISTORICAL_ESTIMATE'       // Historical baseline; no recent check
    | 'INTERNAL_ESTIMATE'         // Internal pricing model; no external data
    | 'USER_PROVIDED_ITINERARY';  // User-pasted itinerary snapshot

// ---------------------------------------------------------------------------
// Thresholds
// ---------------------------------------------------------------------------

/** Snapshot age (minutes) beyond which state becomes STALE */
const STALE_THRESHOLD_MINUTES = 120;

/** Snapshot age (minutes) beyond which state becomes DELAYED (before STALE) */
const DELAYED_THRESHOLD_MINUTES = 90;

/** Expected monitoring check interval in minutes */
const CHECK_INTERVAL_MINUTES = 60;

// ---------------------------------------------------------------------------
// Labels and descriptions (user-facing)
// ---------------------------------------------------------------------------

const STATE_LABELS: Record<MonitoringState, string> = {
    ACTIVE: 'Monitoring active',
    CHECKING: 'Checking now',
    DELAYED: 'Monitoring delayed',
    STALE: 'Snapshot outdated',
    LIMITED_DATA: 'Limited coverage',
    ESTIMATED_ONLY: 'Estimated data only',
    ERROR: 'Monitoring error',
};

const STATE_DESCRIPTIONS: Record<MonitoringState, string> = {
    ACTIVE: 'Periodic checks are running normally. Snapshot is recent.',
    CHECKING: 'A new monitoring snapshot is currently being fetched.',
    DELAYED: 'The expected monitoring check has not arrived yet. This can occur during high-demand periods.',
    STALE: 'The current snapshot is older than expected. Data may not reflect recent price or schedule changes.',
    LIMITED_DATA: 'Monitoring is active but data coverage is incomplete. Some values are inferred from available sources.',
    ESTIMATED_ONLY: 'No provider check has been performed. All data is estimated from your itinerary snapshot.',
    ERROR: 'Monitoring encountered an issue. Data may be incomplete or unavailable.',
};

const DATA_SOURCE_LABELS: Record<MonitoringDataSource, string> = {
    LIVE_PROVIDER_DATA: 'Live provider data',
    PERIODIC_PROVIDER_CHECK: 'Periodic provider check',
    HISTORICAL_ESTIMATE: 'Historical baseline estimate',
    INTERNAL_ESTIMATE: 'Internal estimate',
    USER_PROVIDED_ITINERARY: 'User-provided itinerary snapshot',
};

const DATA_SOURCE_DESCRIPTIONS: Record<MonitoringDataSource, string> = {
    LIVE_PROVIDER_DATA: 'Data sourced directly from the airline or booking provider in near real time.',
    PERIODIC_PROVIDER_CHECK: 'Data sourced from scheduled provider checks. Not a live stream — checks run on a regular interval.',
    HISTORICAL_ESTIMATE: 'Derived from historical route baselines. No recent provider check was performed for this snapshot.',
    INTERNAL_ESTIMATE: 'Generated by internal pricing models. No external provider data was fetched for this snapshot.',
    USER_PROVIDED_ITINERARY: 'Based on the itinerary you provided. No live provider verification was performed.',
};

/** States where strong reassurance wording should be suppressed */
const SUPPRESS_REASSURANCE_STATES: Set<MonitoringState> = new Set([
    'STALE',
    'ESTIMATED_ONLY',
    'ERROR',
    'DELAYED',
]);

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface TrackingStateInput {
    status?: string;
    waitingForNextSnapshot?: boolean;
    limitedData?: boolean;
    realTimeDataUnavailable?: boolean;
    bookingDataEstimated?: boolean;
}

export interface MonitoringContext {
    state: MonitoringState;
    dataSource: MonitoringDataSource;
    snapshotAgeMinutes: number | null;
    lastCheckedAt: Date | null;
    nextExpectedCheck: Date | null;
    isStale: boolean;
    humanReadableAge: string;
    humanReadableNext: string;
    stateLabel: string;
    stateDescription: string;
    dataSourceLabel: string;
    dataSourceDescription: string;
    suppressReassurance: boolean;
}

// ---------------------------------------------------------------------------
// Utility functions
// ---------------------------------------------------------------------------

export function computeSnapshotAgeMinutes(lastChecked: Date | null | undefined): number | null {
    if (!lastChecked) return null;
    const then = new Date(lastChecked).getTime();
    if (isNaN(then)) return null;
    return Math.max(0, Math.floor((Date.now() - then) / 60000));
}

export function formatSnapshotAge(ageMinutes: number | null): string {
    if (ageMinutes === null) return 'Unknown';
    if (ageMinutes < 2) return 'just now';
    if (ageMinutes < 60) return `${ageMinutes} minutes ago`;
    const hours = Math.floor(ageMinutes / 60);
    const mins = ageMinutes % 60;
    if (mins === 0) return `${hours} hour${hours !== 1 ? 's' : ''} ago`;
    return `${hours}h ${mins}m ago`;
}

export function formatNextCheck(nextCheck: Date | null): string {
    if (!nextCheck) return 'Next check time unknown';
    const diffMs = nextCheck.getTime() - Date.now();
    if (diffMs <= 0) return 'Overdue — check pending';
    const diffMin = Math.floor(diffMs / 60000);
    if (diffMin < 2) return 'In less than a minute';
    if (diffMin < 60) return `In ${diffMin} minutes`;
    const hours = Math.floor(diffMin / 60);
    return `In about ${hours} hour${hours !== 1 ? 's' : ''}`;
}

export function resolveMonitoringState(
    trackingState: TrackingStateInput | null | undefined,
    ageMinutes: number | null,
    dataSource: MonitoringDataSource,
): MonitoringState {
    if (!trackingState) return 'ESTIMATED_ONLY';

    const status = (trackingState.status || '').toUpperCase();
    if (status === 'ERROR' || status === 'FAILED') return 'ERROR';
    if (status === 'CHECKING') return 'CHECKING';

    if (
        dataSource === 'INTERNAL_ESTIMATE' ||
        dataSource === 'HISTORICAL_ESTIMATE' ||
        dataSource === 'USER_PROVIDED_ITINERARY'
    ) {
        return 'ESTIMATED_ONLY';
    }

    if (ageMinutes !== null) {
        if (ageMinutes >= STALE_THRESHOLD_MINUTES) return 'STALE';
        if (ageMinutes >= DELAYED_THRESHOLD_MINUTES) return 'DELAYED';
    }

    if (trackingState.limitedData) return 'LIMITED_DATA';

    return 'ACTIVE';
}

export function resolveDataSource(
    scoreDataSourceType?: string | null,
    realTimeDataUnavailable?: boolean | null,
    limitedData?: boolean | null,
): MonitoringDataSource {
    if (
        scoreDataSourceType === 'USER_PASTED_ITINERARY' ||
        scoreDataSourceType === 'USER_PROVIDED_ITINERARY'
    ) {
        if (realTimeDataUnavailable) {
            if (limitedData) return 'HISTORICAL_ESTIMATE';
            return 'USER_PROVIDED_ITINERARY';
        }
        return 'USER_PROVIDED_ITINERARY';
    }
    if (realTimeDataUnavailable) {
        return limitedData ? 'HISTORICAL_ESTIMATE' : 'PERIODIC_PROVIDER_CHECK';
    }
    return 'PERIODIC_PROVIDER_CHECK';
}

export function buildMonitoringContext(
    lastChecked: Date | null | undefined,
    trackingState: TrackingStateInput | null | undefined,
    dataSource: MonitoringDataSource,
): MonitoringContext {
    const snapshotAgeMinutes = computeSnapshotAgeMinutes(lastChecked ?? null);
    const state = resolveMonitoringState(trackingState, snapshotAgeMinutes, dataSource);

    const nextExpectedCheck = lastChecked
        ? new Date(new Date(lastChecked).getTime() + CHECK_INTERVAL_MINUTES * 60 * 1000)
        : null;

    return {
        state,
        dataSource,
        snapshotAgeMinutes,
        lastCheckedAt: lastChecked ? new Date(lastChecked) : null,
        nextExpectedCheck,
        isStale: state === 'STALE',
        humanReadableAge: formatSnapshotAge(snapshotAgeMinutes),
        humanReadableNext: formatNextCheck(nextExpectedCheck),
        stateLabel: STATE_LABELS[state],
        stateDescription: STATE_DESCRIPTIONS[state],
        dataSourceLabel: DATA_SOURCE_LABELS[dataSource],
        dataSourceDescription: DATA_SOURCE_DESCRIPTIONS[dataSource],
        suppressReassurance: SUPPRESS_REASSURANCE_STATES.has(state),
    };
}
